### ISSUE TITLE
Can i use the tool without using nginxPlus

### ISSUE THREAD

**Issue by elixxx** [nginx/nginx-asg-sync#209]
It is not really a feature request, but can use the tool with the normal Nginx without paying for Plus?
For me, it looks like I do not need to pass a license and find no hint if I can use it or not.
Greet
Felix

**Comment by pleshakov** [comment]
Hi @elixxx . The asg-sync leverages the dynamic reconfiguration NGINX Plus API, which isn't available in NGINX OSS. So it is not possible to use asg-sync with NGINX OSS.
